import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsConnectors: SidebarsConfig = {
  connectorsSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'CDK',
      collapsed: false,
      items: [
        'cdk/baseconnector',
        'cdk/basedomain',
        'cdk/basestartup',
        'cdk/cdksettings',
        'cdk/register',
        'cdk/router',
        'cdk/middleware',
      ],
    },
    {
      type: 'category',
      label: 'SimPackage',
      collapsed: false,
      items: [
        'simpackage/simconnector',
        'simpackage/simcontroller',
        'simpackage/slim-models',
        'simpackage/siminterface',
        'simpackage/simulatordomain',
        {
          type: 'category',
          label: 'Spice',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'simpackage/spice', // Path to your spice folder
            },
          ],
        },
      ],
    },
  ],
};

export default sidebarsConnectors;
